### ISSUE TITLE
Getting "SyntaxError: Unexpected token export"

### ISSUE THREAD

**Issue by pencilcheck** [jozanza/next-css-json-loader#1]
Using next-beta.36

In my index.js
```
import styles from '../static/index.css'

export default class extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <h1>Index</h1>
    );
  }
}
```

In my index.css
```
h1 {
  color: red;
}
```

The rest the same setup as in the README.md. Getting the error when trying to run in the dev server from `yarn dev`

**Comment by jozanza** [comment]
@pencilcheck So I created a better solution: https://www.npmjs.com/package/babel-plugin-jsonify-css

Use that babel plugin instead of this webpack loader, and all should be well. Let me know if you run into any other problems.

**Comment by pencilcheck** [comment]
That's cool!
